const TXT={
es:{
  titulo:"Aureliano & Ester · 4 de diciembre de 2026",
  desc:"Te invitamos a celebrar nuestra boda el 4 de diciembre de 2026.",
  ogt:"Aureliano & Ester · Nuestra boda",
  ogd:"Te invitamos a celebrar con nosotros el 4 de diciembre de 2026.",
  hi:"Dos vidas, un solo cordón: con la bendición de Dios celebramos nuestro matrimonio",
  fechaCorta:"4 · DICIEMBRE · 2026",
  verso:"“Y si alguno prevaleciere contra uno, dos le resistirán; y cordón de tres dobleces no se rompe pronto.”",
  citaVerso:"Eclesiastés 4:12",
  hInv:"Nos haría muy felices contar contigo",
  pInv:"Con inmensa alegría invitamos a nuestros familiares y amigos a acompañarnos en el día en que uniremos nuestras vidas ante Dios.",
  fecha:"Fecha",
  fechaLarga:"Viernes 4 de diciembre de 2026",
  hora:"Hora",
  horaTxt:"1:00 p. m.",
  lugarEt:"Lugar",
  addCal:"Agregar al calendario",
  llegar:"Cómo llegar",
  hCuenta:"Falta poco para el gran día",
  dias:"días",
  horas:"horas",
  minutos:"minutos",
  hPadres:"Con la bendición de nuestros padres",
  padresA:"Hijo de<br>Aureliano González y Lidia Arcia",
  padresE:"Hija de<br>Cristóbal Yáñez y Eneida Yáñez",
  hVest:"Código de vestimenta",
  vestTit:"Atuendo típico panameño",
  vestTxt:"Vestido típico, montuno, camisilla y sombrero pintao: te esperamos con lo más lindo de nuestra tradición. Se solicita evitar el color blanco.",
  hReg:"Tu presencia es nuestro mejor regalo",
  pReg:"Si deseas tener un detalle con nosotros, puedes elegir libremente la opción que prefieras.",
  efectivo:"Regalo en efectivo",
  fisico:"Regalo físico",
  o:"o",
  hConf:"¿Nos acompañas?",
  pConf:"Por favor, cuéntanos si podrás asistir.",
  confirmar:"Confirmar asistencia",
  rsvpCorto:"Confirmar",
  hGal:"Nuestra historia",
  cierre:"Gracias por ser parte de este momento tan especial de nuestras vidas.",
  nombre:"Nombre completo",
  personas:"Cantidad de personas",
  asistir:"¿Podrás asistir?",
  si:"Sí asistiré",
  no:"No podré asistir",
  mensaje:"Mensaje para los novios (opcional)",
  enviar:"Enviar confirmación",
  gracias:"¡Gracias por confirmar!",
  gracias2:"Nos hace muy felices contar contigo. ¡Nos vemos el 4 de diciembre!",
  tocaSello:"Toca el sello para abrir",
  errNombre:"Escribe tu nombre completo.",
  errPersonas:"Indica entre 1 y 10 personas.",
  errAsistir:"Elige si podrás asistir.",
  enviando:"Enviando…",
  errEnvio:"No pudimos enviar tu respuesta. Revisa tu conexión e inténtalo de nuevo.",
  hoy:"¡Hoy es el gran día!",
  ampliar:"Ampliar foto {n}",
  fotoAlt:"Foto {n} de la galería",
  fotoDe:"Foto {n} de {t}",
  diaBoda:"{d} de {m}, día de la boda",
  mesAnio:"{m} de {y}",
  meses:["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
  dsem:["D", "L", "M", "M", "J", "V", "S"],
  icsTitulo:"Boda de Aureliano y Ester",
  sinMusica:"Agrega tu canción en CONFIG.musica",
  errAudio:"No se pudo reproducir el audio",
  play:"Reproducir música",
  pausa:"Pausar música",
  cerrar:"Cerrar",
  anterior:"Anterior",
  siguiente:"Siguiente",
  visor:"Visor de fotos",
  abrir:"Abrir invitación",
  nombresAria:"Aureliano y Ester",
  altCover:"Foto de Aureliano y Ester",
  altVest:"Ejemplo del atuendo típico panameño",
  cuentaAria:"Tiempo restante para la boda",
  calAria:"Calendario de la fecha de la boda",
  mapaTitulo:"Mapa: ubicación de la ceremonia",
  idiomaAria:"Idioma"
},
en:{
  titulo:"Aureliano & Ester · December 4, 2026",
  desc:"We invite you to celebrate our wedding on December 4, 2026.",
  ogt:"Aureliano & Ester · Our wedding",
  ogd:"We invite you to celebrate with us on December 4, 2026.",
  hi:"Two lives, one cord: with God's blessing, we celebrate our marriage",
  fechaCorta:"DECEMBER 4 · 2026",
  verso:"“And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken.”",
  citaVerso:"Ecclesiastes 4:12",
  hInv:"It would make us so happy to have you with us",
  pInv:"With immense joy, we invite our family and friends to join us on the day we unite our lives before God.",
  fecha:"Date",
  fechaLarga:"Friday, December 4, 2026",
  hora:"Time",
  horaTxt:"1:00 p.m.",
  lugarEt:"Venue",
  addCal:"Add to calendar",
  llegar:"Get directions",
  hCuenta:"The big day is almost here",
  dias:"days",
  horas:"hours",
  minutos:"minutes",
  hPadres:"With the blessing of our parents",
  padresA:"Son of<br>Aureliano González and Lidia Arcia",
  padresE:"Daughter of<br>Cristóbal Yáñez and Eneida Yáñez",
  hVest:"Dress code",
  vestTit:"Traditional Panamanian attire",
  vestTxt:"Vestido típico, montuno, camisilla and sombrero pintao (traditional Panamanian dress): we look forward to seeing you in the best of our tradition.Please refrain from wearing white.",
  hReg:"Your presence is our greatest gift",
  pReg:"If you would like to give us a gift, you are free to choose whichever option you prefer.",
  efectivo:"Cash gift",
  fisico:"Physical gift",
  o:"or",
  hConf:"Will you join us?",
  pConf:"Please let us know if you will be able to attend.",
  confirmar:"Confirm attendance",
  rsvpCorto:"RSVP",
  hGal:"Our story",
  cierre:"Thank you for being part of this very special moment in our lives.",
  nombre:"Full name",
  personas:"Number of guests",
  asistir:"Will you attend?",
  si:"Yes, I will attend",
  no:"No, I will not be able to attend",
  mensaje:"Message for the couple (optional)",
  enviar:"Send RSVP",
  gracias:"Thank you for confirming!",
  gracias2:"It makes us so happy to have you with us. See you on December 4!",
  tocaSello:"Tap the seal to open",
  errNombre:"Please enter your full name.",
  errPersonas:"Enter between 1 and 10 guests.",
  errAsistir:"Please choose whether you can attend.",
  enviando:"Sending…",
  errEnvio:"We could not send your response. Check your connection and try again.",
  hoy:"Today is the big day!",
  ampliar:"Enlarge photo {n}",
  fotoAlt:"Photo {n} of the gallery",
  fotoDe:"Photo {n} of {t}",
  diaBoda:"{m} {d}, wedding day",
  mesAnio:"{m} {y}",
  meses:["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  dsem:["S", "M", "T", "W", "T", "F", "S"],
  icsTitulo:"Wedding of Aureliano and Ester",
  sinMusica:"Add your song in CONFIG.musica",
  errAudio:"The audio could not be played",
  play:"Play music",
  pausa:"Pause music",
  cerrar:"Close",
  anterior:"Previous",
  siguiente:"Next",
  visor:"Photo viewer",
  abrir:"Open invitation",
  nombresAria:"Aureliano and Ester",
  altCover:"Photo of Aureliano and Ester",
  altVest:"Example of traditional Panamanian attire",
  cuentaAria:"Time remaining until the wedding",
  calAria:"Calendar showing the wedding date",
  mapaTitulo:"Map: ceremony location",
  idiomaAria:"Language"
}
};
